# Generated by Django 4.1 on 2022-08-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_category_alter_movie_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Режиссер',
                'verbose_name_plural': 'Режиссеры',
            },
        ),
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актеры', 'verbose_name_plural': 'Актеры'},
        ),
        migrations.RemoveField(
            model_name='actor',
            name='age',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='url',
        ),
    ]
