# Generated by Django 4.1 on 2022-08-19 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_directors_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='directors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='film_actor', to='movies.actor', verbose_name='актеры'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='film_director', to='movies.actor', verbose_name='режиссер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.genre', verbose_name='жанры'),
            preserve_default=False,
        ),
    ]
