# Generated by Django 4.1 on 2022-08-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_movie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='premiere',
            field=models.BooleanField(default=False, verbose_name='Премьера'),
        ),
    ]
