# Generated by Django 4.1 on 2022-08-23 15:29

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_movie_premiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
