# Generated by Django 4.1 on 2022-08-26 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_video_description_video_image_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Фильм'),
        ),
    ]
