# Generated by Django 4.1 on 2022-08-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_video_video_film'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_film',
            new_name='movie',
        ),
    ]
